<a href="https://colab.research.google.com/github/sanchita-star/Python_Dailyques/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim) #dimension
print(arr.shape) #rows and columns
print(arr.size) #ele num
print(arr.dtype) # data types

2
(2, 3)
6
int64


In [ ]:
#indexing and slicing
#1D indexing
arr=np.array([10,20,30,40])
print(arr[2])
#2D indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

30
6


In [ ]:
#slicing
b=np.array([10,20,30,40,50])
print(b[2:4])

[30 40]


In [ ]:
#operation
ar=np.array([10,20,30,40,50])
print(ar[1] * 10 *ar[3])
print(ar[3] +3% ar[4])

8000
43


In [ ]:
#for 1D array
a1=np.array([1,2])
a2=np.array([3,4])
a=np.concatenate([a1,a2])
print(a)
#for 2D array
b=np.array([[1,2]])
c=np.array([[3,4]])
print(np.concatenate((b,c),axis=0)) #rowwise
print(np.concatenate((b,c),axis=1))

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 3 4]]


In [ ]:
#reshaping array
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#splitting arrays
arr=np.array([10,20,30,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]
